version: '3.3'

services:
  ekascribe-web-ai:
    image: '${TAG}'
    environment:
      - ekascribe_web_app_env=${app_env}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - AWS_STS_REGIONAL_ENDPOINTS=${AWS_STS_REGIONAL_ENDPOINTS}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

    container_name: ekascribe-web-ai
    healthcheck:
      test: ['CMD-SHELL', "curl --location --request GET 'http://localhost/'"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '8080:80'

    command: ['node', 'server.js']
    volumes:
      - /var/run/secrets/eks.amazonaws.com/serviceaccount/:/var/run/secrets/eks.amazonaws.com/serviceaccount/
