version: '3.3'

services:
  ekascribe-web:
    image: '${TAG}'
    environment:
      - ekascribe_web_app_env=${app_env}
    container_name: ekascribe-web
    healthcheck:
      test: ['CMD-SHELL', "curl --location --request GET 'http://localhost/'"]
      interval: 10s
      timeout: 5s
      retries: 3

    ports:
      - '3000:80'

    command: ['node', 'server.js']
