apiVersion: v1
kind: Service
metadata:
  name: ekascribe-web
  namespace: eka-care
  labels:
    app.kubernetes.io/name: ekascribe-web
    app.kubernetes.io/part-of: ekascribe
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ekascribe-web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
