apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: varta-gw
  namespace: eka-care
spec:
  selector:
    istio: ingressgateway
  servers:
  # Port 80 stays open but only answers with a 301 to https.
  - hosts:
    - vaarta.bharatai.gov.in
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: false
  - hosts:
    - vaarta.bharatai.gov.in
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: varta-tls
      #credentialName: varta-tls-emudhra2
---
# 4. Route to the app.
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: varta-vs
  namespace: eka-care
spec:
  gateways:
  - varta-gw
  hosts:
  - varta.bharatai.gov.in
  - vaarta.bharatai.gov.in

  http:
  - route:
    - destination:
        host: ekascribe-api.eka-care.svc.cluster.local
        port:
          number: 8000
