from .result_router import status_api_router_v3
from .transactions import transaction_router
from .language_config import language_config_router
from .consent_api import consent_router
from .metrics import metrics_router
from .template_api import template_router
from .template_result import template_result_router
from .swagger_docs import swagger_router
from .integrations import integrations_router
from .testimonials import testimonials_router