import { MODEL_TYPE } from './enums';
import { TPreferenceItem } from './types';

const env = (process.env.NEXT_PUBLIC_ENV || 'PROD') as 'DEV' | 'PROD';

export const SUPPORTED_LANGUAGES: TPreferenceItem[] = [
  { id: 'en-IN', name: 'English (India)' },
  { id: 'en-US', name: 'English (United States)' },
  { id: 'hi', name: 'Hindi' },
  { id: 'gu', name: 'Gujarati' },
  { id: 'kn', name: 'Kannada' },
  { id: 'ml', name: 'Malayalam' },
  { id: 'ta', name: 'Tamil' },
  { id: 'te', name: 'Telugu' },
  { id: 'bn', name: 'Bengali' },
  { id: 'mr', name: 'Marathi' },
  { id: 'pa', name: 'Punjabi' },
  { id: 'as', name: 'Assamese' },
  { id: 'auto_detect', name: 'Auto Detect Language' },
];

export const SUPPORTED_OUTPUT_FORMATS_PROD: TPreferenceItem[] = [
  {
    id: '9d9675c6-b29b-424a-abac-99ddd3b8909c',
    name: 'Clinical Notes',
    template_type: 'custom',
  },
];

export const SUPPORTED_OUTPUT_FORMATS_DEV: TPreferenceItem[] = [
  {
    id: '3d707c1c-311e-4424-80e9-e5d7a229d519',
    name: 'SOAP Notes',
    template_type: 'custom',
  },
];

export const SUPPORTED_OUTPUT_FORMATS =
  env === 'PROD' ? SUPPORTED_OUTPUT_FORMATS_PROD : SUPPORTED_OUTPUT_FORMATS_DEV;

export const CONSULTATION_MODES: TPreferenceItem[] = [
  {
    id: 'consultation',
    name: 'Consultation',
    desc: 'Eka Scribe will listen to your conversation and create clinical notes',
  },
  {
    id: 'dictation',
    name: 'Dictation',
    desc: 'Dictate your notes to Eka Scribe and create clinical notes',
  },
];

export const SUPPORTED_MODELS: TPreferenceItem[] = [
  {
    id: MODEL_TYPE.PRO,
    name: 'Pro',
    desc: 'Our best model, built for maximum accuracy, may take a little longer.',
  },
  {
    id: MODEL_TYPE.LITE,
    name: 'Lite',
    desc: 'Lightweight, faster results with balanced accuracy.',
  },
];

export const SUPPORTED_SPECIALIZATIONS: TPreferenceItem[] = [
  { id: 'critical-care-specialist', name: 'Critical care specialist' },
  { id: 'intensivist', name: 'Intensivist' },
  { id: 'sleep-medicine', name: 'Sleep Medicine' },
  { id: 'emergency-medicine-specialist', name: 'Emergency medicine specialist' },
  { id: 'anaesthaetist', name: 'Anaesthaetist' },
  { id: 'sports-medicine', name: 'Sports Medicine' },
  { id: 'dietician', name: 'Dietician' },
  { id: 'plastic-surgeon', name: 'Plastic Surgeon' },
  { id: 'vitreoretinal-surgeon', name: 'Vitreoretinal Surgeon' },
  { id: 'infertility-specialist', name: 'Infertility specialist' },
  { id: 'sexologist', name: 'Sexologist' },
  { id: 'pathologist', name: 'Pathologist' },
  { id: 'paediatric-surgeon', name: 'Paediatric Surgeon' },
  { id: 'fetal-medicine-specialist', name: 'Fetal Medicine Specialist' },
  { id: 'neurologist', name: 'Neurologist' },
  { id: 'neurophysician', name: 'Neurophysician' },
  { id: 'cosmetologist', name: 'Cosmetologist' },
  { id: 'trichologist', name: 'Trichologist' },
  { id: 'vascular-surgeon', name: 'Vascular Surgeon' },
  { id: 'spine-surgeon', name: 'Spine Surgeon' },
  { id: 'ayurveda', name: 'Ayurveda' },
  { id: 'homeopathy-physician', name: 'Homeopathy physician' },
  { id: 'naturopathy-physician', name: 'Naturopathy Physician' },
  { id: 'unani-physician', name: 'Unani Physician' },
  { id: 'chiropractor', name: 'Chiropractor' },
  { id: 'nephrologist', name: 'Nephrologist' },
  { id: 'urologist', name: 'Urologist' },
  { id: 'immunologist', name: 'Immunologist' },
  { id: 'rheumatologist', name: 'Rheumatologist' },
  { id: 'neonatologist', name: 'Neonatologist' },
  { id: 'surgical-gastroenterologist', name: 'Surgical Gastroenterologist' },
  { id: 'medical-gastroenterologist', name: 'Medical Gastroenterologist' },
  { id: 'physiotherapist', name: 'Physiotherapist' },
  { id: 'haematologist', name: 'Haematologist' },
  { id: 'transfusion-medicine', name: 'Transfusion Medicine' },
  { id: 'functional-medicine', name: 'Functional Medicine' },
  { id: 'andrologist', name: 'Andrologist' },
  { id: 'medical-oncologist', name: 'Medical Oncologist' },
  { id: 'surgical-oncologist', name: 'Surgical Oncologist' },
  { id: 'maxillo-facial-surgeon', name: 'Maxillo facial surgeon' },
  { id: 'periodontist', name: 'Periodontist' },
  { id: 'endodontist', name: 'Endodontist' },
  { id: 'psychologist', name: 'Psychologist' },
  { id: 'forensic-medicine-specialist', name: 'Forensic Medicine Specialist' },
  { id: 'public-health-specialist', name: 'Public Health Specialist' },
  { id: 'microbiologist', name: 'Microbiologist' },
  { id: 'specialised-in-pharmacology', name: 'Specialised in Pharmacology' },
  { id: 'specialised-in-anatomy', name: 'Specialised in Anatomy' },
  { id: 'specialised-in-biochemistry', name: 'Specialised in Biochemistry' },
  { id: 'general-physician', name: 'General Physician' },
  { id: 'general-physician-non-mbbs', name: 'General Physician (Non MBBS)' },
  { id: 'internal-medicine', name: 'Internal Medicine' },
  { id: 'obstetrician', name: 'Obstetrician' },
  { id: 'gynaecologist', name: 'Gynaecologist' },
  { id: 'gastroenterologist', name: 'Gastroenterologist' },
  { id: 'nephrology', name: 'Nephrology' },
  { id: 'cardiologist', name: 'Cardiologist' },
  { id: 'pulmonogist', name: 'Pulmonogist' },
  { id: 'paediatrician', name: 'Paediatrician' },
  { id: 'orthopaedician', name: 'Orthopaedician' },
  { id: 'general-surgeon', name: 'General Surgeon' },
  { id: 'ophthalmologist', name: 'Ophthalmologist' },
  { id: 'ent-specialist', name: 'ENT Specialist' },
  { id: 'radiologist', name: 'Radiologist' },
  { id: 'psychiatrist', name: 'Psychiatrist' },
  { id: 'oncologist', name: 'Oncologist' },
  { id: 'dentist', name: 'Dentist' },
  { id: 'dermatologist', name: 'Dermatologist' },
  { id: 'endocrinologist', name: 'Endocrinologist' },
  { id: 'non-medical', name: 'Non Medical' },
  { id: 'other', name: 'Other' },
];

export const SUPPORTED_EMRS: TPreferenceItem[] = [
  { id: 'ace-health-solutions', name: 'Ace Health Solutions' },
  { id: 'advancedmd', name: 'AdvancedMD' },
  { id: 'allscripts', name: 'Allscripts' },
  { id: 'amazing-charts', name: 'Amazing Charts' },
  { id: 'athenahealth', name: 'athenahealth' },
  { id: 'attune-technologies', name: 'Attune Technologies' },
  { id: 'bestdoc', name: 'BestDoc' },
  { id: 'birlamedisoft', name: 'Birlamedisoft' },
  { id: 'carecloud', name: 'CareCloud' },
  { id: 'cerner-oracle-health', name: 'Cerner Oracle Health' },
  { id: 'chartlogic', name: 'ChartLogic' },
  { id: 'chirotouch', name: 'ChiroTouch' },
  { id: 'cloudnine', name: 'Cloudnine' },
  { id: 'compurx-infotech', name: 'CompuRx Infotech' },
  { id: 'compulink', name: 'Compulink' },
  { id: 'cpsi', name: 'CPSI' },
  { id: 'curemd', name: 'CureMD' },
  { id: 'dentrix', name: 'Dentrix' },
  { id: 'docengage', name: 'DocEngage' },
  { id: 'docon', name: 'DocOn' },
  { id: 'docpulse', name: 'DocPulse' },
  { id: 'drchrono', name: 'DrChrono' },
  { id: 'eka-care', name: 'Eka Care' },
  { id: 'elation-health', name: 'Elation Health' },
  { id: 'ema-by-modernizing-medicine', name: 'EMA by Modernizing Medicine' },
  { id: 'eclinicalworks', name: 'eClinicalWorks' },
  { id: 'ehospital-systems', name: 'eHospital Systems' },
  { id: 'epic', name: 'Epic' },
  { id: 'ezovion', name: 'Ezovion' },
  { id: 'greenway-health', name: 'Greenway Health' },
  { id: 'harris-healthcare', name: 'Harris Healthcare' },
  { id: 'healthplix', name: 'HealthPlix' },
  { id: 'healthray', name: 'Healthray' },
  { id: 'inicu', name: 'iNICU' },
  { id: 'insta-by-practo', name: 'Insta by Practo' },
  { id: 'intellimed', name: 'IntelliMed' },
  { id: 'jeevanti', name: 'Jeevanti' },
  { id: 'kareo', name: 'Kareo' },
  { id: 'lybrate', name: 'Lybrate' },
  { id: 'matrixcare', name: 'MatrixCare' },
  { id: 'medevolve', name: 'MedEvolve' },
  { id: 'medhost', name: 'Medhost' },
  { id: 'meditech', name: 'MEDITECH' },
  { id: 'medixcel', name: 'Medixcel' },
  { id: 'medmantra', name: 'Medmantra' },
  { id: 'medmind-technologies', name: 'MedMind Technologies' },
  { id: 'modmed', name: 'ModMed' },
  { id: 'mocdoc', name: 'MocDoc' },
  { id: 'nephroplus', name: 'NephroPlus' },
  { id: 'netsmart', name: 'Netsmart' },
  { id: 'nextech', name: 'Nextech' },
  { id: 'nextgen-healthcare', name: 'NextGen Healthcare' },
  { id: 'nicksoft', name: 'NICKSoft' },
  { id: 'office-practicum', name: 'Office Practicum' },
  { id: 'open-dental', name: 'Open Dental' },
  { id: 'paras-hmis', name: 'Paras HMIS' },
  { id: 'pcc-pediatric-solutions', name: 'PCC Pediatric Solutions' },
  { id: 'pointclickcare', name: 'PointClickCare' },
  { id: 'practice-fusion', name: 'Practice Fusion' },
  { id: 'practo', name: 'Practo' },
  { id: 'praxis-emr', name: 'Praxis EMR' },
  { id: 'prognocis', name: 'PrognoCIS' },
  { id: 'remedy-hms', name: 'Remedy HMS' },
  { id: 'sevocity', name: 'Sevocity' },
  { id: 'simplepractice', name: 'SimplePractice' },
  { id: 'softclinic', name: 'SoftClinic' },
  { id: 'therapynotes', name: 'TherapyNotes' },
  { id: 'trakcare', name: 'TrakCare' },
  { id: 'veradigm', name: 'Veradigm' },
  { id: 'webpt', name: 'WebPT' },
  { id: 'other', name: 'Other' },
];

export const TRANSCRIPTION_LANGUAGES: TPreferenceItem[] = [
  { id: 'raw', name: 'Original' },
  { id: 'eng', name: 'English' },
  { id: 'hi', name: 'Hindi' },
  { id: 'gu', name: 'Gujarati' },
  { id: 'kn', name: 'Kannada' },
  { id: 'ml', name: 'Malayalam' },
  { id: 'ta', name: 'Tamil' },
  { id: 'te', name: 'Telugu' },
  { id: 'bn', name: 'Bengali' },
  { id: 'mr', name: 'Marathi' },
  { id: 'pa', name: 'Punjabi' },
];
