import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { getFirestore, Firestore } from 'firebase/firestore';
import { getAuth, signInWithCustomToken, onAuthStateChanged, Auth, User } from 'firebase/auth';

const getFirebaseConfig = () => ({
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
});

let app: FirebaseApp;
let db: Firestore;
let auth: Auth;

export const initializeFirebase = (): FirebaseApp => {
  if (!getApps().length) {
    app = initializeApp(getFirebaseConfig());
  } else {
    app = getApps()[0];
  }
  return app;
};

export const getFirebaseAuth = (): Auth => {
  if (!auth) {
    const app = initializeFirebase();
    auth = getAuth(app);
  }
  return auth;
};

export const getFirestoreDB = (): Firestore => {
  if (!db) {
    const app = initializeFirebase();
    // Connect to the named 'doctool' database, not the default
    db = getFirestore(app, 'doctool');
  }
  return db;
};

/**
 * Sign in to Firebase using a custom token from your backend
 * @param customToken - The custom token generated by your backend
 */
export const signInToFirebase = async (customToken: string): Promise<User> => {
  const auth = getFirebaseAuth();
  const userCredential = await signInWithCustomToken(auth, customToken);
  return userCredential.user;
};

/**
 * Get the current Firebase user
 */
export const getCurrentFirebaseUser = (): User | null => {
  const auth = getFirebaseAuth();
  return auth.currentUser;
};

/**
 * Check if user is authenticated with Firebase
 */
export const isFirebaseAuthenticated = (): boolean => {
  return getCurrentFirebaseUser() !== null;
};

/**
 * Listen to Firebase auth state changes
 */
export const onFirebaseAuthStateChanged = (callback: (user: User | null) => void): (() => void) => {
  const auth = getFirebaseAuth();
  return onAuthStateChanged(auth, callback);
};
