"""
Summary Agent

This agent generates comprehensive patient summaries from multiple
consultation clinical notes (generated by TemplateGenerationAgent),
synthesizing longitudinal patient history.
"""

from echo.agents.generic_agent import GenericAgent
from echo import AgentConfig as EchoAgentConfig, PersonaConfig, TaskConfig
from echo.models.user_conversation import (
    ConversationContext,
    Message,
    MessageRole,
    TextMessage,
)
from .agent_config import LLMAgentConfig
from voice2rx.utils.json_normalization import normalize_whitespace
from voice2rx.services.prompts import get_prompt_service
from logs.custom_logger import get_logger

logger = get_logger(__name__)


class SummaryAgent:
    """Agent for patient summary generation. Config from Langfuse or voice2rx/agents/prompts fallback."""

    @staticmethod
    def create_agent_config(final_prompt: str) -> EchoAgentConfig:
        prompt_svc = get_prompt_service()
        parsed = prompt_svc.get_parsed_agent_prompt("summary")
        role = parsed.role()
        goal = parsed.goal
        backstory = parsed.full_backstory()
        expected_output = parsed.expected_output_for("markdown")
        return EchoAgentConfig(
            persona=PersonaConfig(role=role, goal=goal, backstory=backstory),
            task=TaskConfig(description=final_prompt, expected_output=expected_output),
        )

    @staticmethod
    async def generate(
        clinical_notes_text: str,
        agent_config: LLMAgentConfig,
        request_id: str = "summary",
    ) -> str:
        """
        Generate patient summary from structured clinical notes.

        Args:
            clinical_notes_text: Concatenated clinical notes from multiple sessions
            agent_config: LLM configuration
            request_id: Unique request ID for tracing

        Returns:
            Markdown formatted patient summary
        """
        prompt_svc = get_prompt_service()
        parsed = prompt_svc.get_parsed_agent_prompt(
            "summary", clinical_notes=clinical_notes_text
        )
        final_prompt = parsed.user_prompt
        echo_agent_config = SummaryAgent.create_agent_config(final_prompt)
        llm_config = agent_config.to_llm_config()

        agent = GenericAgent(agent_prompt=echo_agent_config, llm_config=llm_config)

        context = ConversationContext()
        context.add_message(
            Message(
                role=MessageRole.USER,
                content=[TextMessage(text=final_prompt)],
            )
        )

        result = await agent.run(context, out_msg_id=request_id)
        return normalize_whitespace(result.llm_response.text)
